from pandas import read_table
from pathlib import Path


##### setup config #####
configfile: "../config/config.yaml"


sample_file = Path.joinpath(Path(".."), Path(config["sample_file"]))
samples = read_table(sample_file)["sample_name"].tolist()


##### load rules #####
include: "rules/reference.smk"
include: "rules/align.smk"
include: "rules/variants_bcftools.smk"
include: "rules/variants_mutserve.smk"
include: "rules/analysis.smk"
include: "rules/helper.smk"
include: "rules/consensus_sequence.smk"


# Executing all rules for complete analysis
# Works for Human, Mouse and dog mitochondrial data
rule all:
    input:
        expand(
            "results/calls_bcftools/{reference}/norm_{sample}.vcf.gz",
            caller="bcftools",
            sample=samples,
            reference=config["reference"],
        ),
        expand(
            "results/calls_{caller}/{reference}/merged.vcf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/calls_{caller}/{reference}/commonVariants.tsv",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/ref_heatmap.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/ref_heatmap_clusterrow.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/alt_heatmap.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/alt_heatmap_clusterrow.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/sequences/{caller}/{reference}/{sample}.fa",
            caller="bcftools",
            sample=samples,
            reference=config["reference"],
        ),
    log:
        "logs/all.log",


# Executing all rules for complete analysis for Human mitochondrial data
# adds extra the step of calling the mitochondrial variants with mutserve
# mutserve executable hast to be installed and in the path mutserve/
rule all_human:
    input:
        expand(
            "results/calls_{caller}/{reference}/norm_{sample}.vcf.gz",
            caller="bcftools",
            sample=samples,
            reference=config["reference"],
        ),
        expand(
            "results/calls_{caller}/{reference}/merged.vcf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/calls_{caller}/{reference}/commonVariants.tsv",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/ref_heatmap.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/ref_heatmap_clusterrow.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/alt_heatmap.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/plots/{caller}/{reference}/alt_heatmap_clusterrow.pdf",
            caller="bcftools",
            reference=config["reference"],
        ),
        expand(
            "results/sequences/{caller}/{reference}/{sample}.fa",
            caller="bcftools",
            sample=samples,
            reference=config["reference"],
        ),
        # mutserve:
        expand(
            "results/calls_{caller}/{reference}/{sample}.vcf.gz",
            caller="mutserve",
            sample=samples,
            reference=config["reference"],
        ),
        expand(
            "results/calls_{caller}/{reference}/merged.vcf",
            caller="mutserve",
            reference=config["reference"],
        ),
