name: Test

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "--lint"
